version: '3'

services:
  account:
    build:
      context: ./account-service
      dockerfile: ./Dockerfile
    image: my-account-service
    ports:
      - "5000:3000"
    command: ["yarn", "dev"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.account.rule=Host(`api.example.com`) && PathPrefix(`/account`)"
      - "traefik.http.services.account.loadbalancer.server.port=3000"

      # - "traefik.enable=true"
      # - "traefik.http.routers.account.rule=Host(`example.com`) && PathPrefix(`/account`)"
      - "traefik.http.middlewares.account-stripprefix.stripprefix.prefixes=/account"
      - "traefik.http.routers.account.middlewares=account-stripprefix@docker"

  catalog:
    build:
      context: ./catalog-service
      dockerfile: ./Dockerfile
    image: my-catalog-service
    ports:
      - "5001:3001"
    command: ["yarn", "dev"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catalog.rule=Host(`api.example.com`) && Path(`/`)"
      - "traefik.http.services.catalog.loadbalancer.server.port=3001"

  media:
    build:
      context: ./media-service
      dockerfile: ./Dockerfile
    image: my-media-service
    ports:
      - "5002:3002"
    command: ["yarn", "dev"]
    
networks:
  default:
    external:
      name: traefik_network