version: '3'

services:
  account-service:
    build:
      context: ./account-service
      dockerfile: ./Dockerfile
    image: my-account-service
    ports:
      - "5000:3000"
    command: ["yarn", "dev"]      

  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: ./Dockerfile
    image: my-catalog-service
    ports:
      - "5001:3001"
    command: ["yarn", "dev"]

  media-service:
    build:
      context: ./media-service
      dockerfile: ./Dockerfile
    image: my-media-service
    ports:
      - "5002:3002"
    command: ["yarn", "dev"]
    
networks:
  default:
    external:
      name: traefik_network