version: '3'

services:

  frontend:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.traefik.entrypoints=http"

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`myhost.mydomain.org`) && PathPrefix(`/catalog`)"

  whoamiv2:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - traefik.http.routers.whoamiv2.entrypoints=http
      - traefik.http.routers.whoamiv2.rule=Host(`myhost.mydomain.org`) && PathPrefix(`/whoami`)

  mysql:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: false
    ports:
      - "33066:3306"
    volumes: 
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql

  redis:
    image: redis:7
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./.docker/redis.conf:/etc/redis/redis.conf
    ports:
      - '6379:6379'

networks:
  default:
    name: traefik_network
    driver: bridge