version: '3'

services:
  account:
    build:
      context: ./account-service
      dockerfile: ./Dockerfile
    image: my-account-service
    ports:
      - "5000:3000"
    command: ["yarn", "dev"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.account.rule=Path(`/`)"
      - "traefik.http.services.account.loadbalancer.server.port=3000"

  catalog:
    build:
      context: ./catalog-service
      dockerfile: ./Dockerfile
    image: my-catalog-service
    ports:
      - "5001:3001"
    command: ["yarn", "dev"]

  media:
    build:
      context: ./media-service
      dockerfile: ./Dockerfile
    image: my-media-service
    ports:
      - "5002:3002"
    command: ["yarn", "dev"]
    
networks:
  default:
    external:
      name: traefik_network