version: '3'

services:

  frontend:
    build:
      context: ./react-app
      dockerfile: ./Dockerfile
    image: react-app-frontend
    ports:
      - "8000:8000"
    command: ["yarn", "dev"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`example.com`) && Path(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=8000"

  account:
    build:
      context: ./account-service
      dockerfile: ./Dockerfile
    image: my-account-service
    ports:
      - "5000:3000"
    command: ["yarn", "dev"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.account.rule=Host(`api.example.com`) && PathPrefix(`/account`)"
      - "traefik.http.services.account.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.account-stripprefix.stripprefix.prefixes=/account"
      - "traefik.http.routers.account.middlewares=account-stripprefix@docker"

  catalog:
    build:
      context: ./catalog-service
      dockerfile: ./Dockerfile
    image: my-catalog-service
    ports:
      - "5001:3001"
    command: ["yarn", "dev"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catalog.rule=Host(`api.example.com`) && Path(`/catalog`)"
      - "traefik.http.services.catalog.loadbalancer.server.port=3001"
      - "traefik.http.middlewares.catalog-stripprefix.stripprefix.prefixes=/catalog"
      - "traefik.http.routers.catalog.middlewares=catalog-stripprefix@docker"

  media:
    build:
      context: ./media-service
      dockerfile: ./Dockerfile
    image: my-media-service
    ports:
      - "5002:3002"
    command: ["yarn", "dev"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=Host(`api.example.com`) && PathPrefix(`/media`)"
      - "traefik.http.services.media.loadbalancer.server.port=3002"
      - "traefik.http.middlewares.media-stripprefix.stripprefix.prefixes=/media"
      - "traefik.http.routers.media.middlewares=media-stripprefix@docker"
    
networks:
  default:
    external:
      name: traefik_network